version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: psqldb
    volumes:
      - ./sql:/sql
      - ./csv:/csv
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hotdog123
      POSTGRES_DB: db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      # Mapping 8001 localhost port to port 5432 of container
      - 8001:5432
    restart: unless-stopped

  keydb:
    image: eqalpha/keydb:latest
    container_name: keydb
    ports:
      - 6379:6379
    command: ["keydb-server", "/etc/keydb/keydb.conf"]
    restart: unless-stopped
